"""Modified Blog model migrations

Revision ID: 33a5ab6cd57c
Revises: 14b836c290a5
Create Date: 2024-04-29 21:50:52.874493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33a5ab6cd57c'
down_revision: Union[str, None] = '14b836c290a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
