"""first_name field name corrected

Revision ID: 8a02df1535a2
Revises: 6711a46ca1cb
Create Date: 2024-04-29 09:46:41.309596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a02df1535a2'
down_revision: Union[str, None] = '6711a46ca1cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(), nullable=True))
    op.drop_column('user', 'first_anme')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_anme', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
